# Generated by Django 5.2.3 on 2025-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free_wifi', 'Free WiFi'), ('parking', 'Parking'), ('outdoor_swimming_pool', 'Outdoor Swimming Pool'), ('cleaning_service', 'Cleaning Service'), ('safety_and_security', 'Safety and Security'), ('private_bathroom', 'Private Bathroom'), ('reception_services', 'Reception Services'), ('entertainment', 'Entertainment'), ('business_facilities', 'Business Facilities'), ('food_and_drink', 'Food and Drink')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=200)),
                ('star_rating', models.DecimalField(decimal_places=1, default=10, help_text='Rating between 0.0 and 10', max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('dormitory', 'Dormitory')], default='standard', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('price', models.FloatField(default=1000.0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('address', models.TextField(max_length=300)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('under_maintenance', 'Under Maintenance'), ('closed', 'Closed')], default='available', max_length=30)),
                ('facilities', models.ManyToManyField(blank=True, to='hotelApp.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
