# Generated by Django 5.2.3 on 2025-06-30 09:14

import django.contrib.auth.mixins
import django.contrib.auth.views
import django.contrib.messages.views
import django.db.models.deletion
import django.views.generic.base
import django.views.generic.detail
import django.views.generic.edit
import django.views.generic.list
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotelApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDeleteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.contrib.messages.views.SuccessMessageMixin, django.views.generic.edit.DeleteView),
        ),
        migrations.CreateModel(
            name='BookingListView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='BookingUpdateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.contrib.messages.views.SuccessMessageMixin, django.views.generic.edit.UpdateView),
        ),
        migrations.CreateModel(
            name='HotelBookView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.views.generic.edit.CreateView),
        ),
        migrations.CreateModel(
            name='HotelCreateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.contrib.messages.views.SuccessMessageMixin, django.views.generic.edit.CreateView),
        ),
        migrations.CreateModel(
            name='HotelDeleteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.contrib.messages.views.SuccessMessageMixin, django.views.generic.edit.DeleteView),
        ),
        migrations.CreateModel(
            name='HotelDetailView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.views.generic.detail.DetailView),
        ),
        migrations.CreateModel(
            name='HotelListView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='HotelUpdateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.contrib.messages.views.SuccessMessageMixin, django.views.generic.edit.UpdateView),
        ),
        migrations.CreateModel(
            name='PaymentCreateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.views.generic.edit.CreateView),
        ),
        migrations.CreateModel(
            name='RegistrationView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.messages.views.SuccessMessageMixin, models.Model, django.views.generic.edit.CreateView),
        ),
        migrations.CreateModel(
            name='RoomCreateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.contrib.messages.views.SuccessMessageMixin, django.views.generic.edit.CreateView),
        ),
        migrations.CreateModel(
            name='RoomDeleteView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.contrib.messages.views.SuccessMessageMixin, django.views.generic.edit.DeleteView),
        ),
        migrations.CreateModel(
            name='RoomUpdateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.contrib.messages.views.SuccessMessageMixin, django.views.generic.edit.UpdateView),
        ),
        migrations.CreateModel(
            name='UserLoginView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django.contrib.auth.views.LoginView),
        ),
        migrations.CreateModel(
            name='UserLogoutView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django.contrib.auth.views.LogoutView),
        ),
        migrations.CreateModel(
            name='UserProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, models.Model, django.views.generic.base.TemplateView),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_persons', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotelApp.room')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='pending', max_length=30)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('paypal', 'PayPal'), ('cash', 'Cash')], default='credit_card', max_length=30)),
                ('transaction_id', models.CharField(max_length=12, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookingApp.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
